// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: api/eason/eason.proto

package eason

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SvrName   string `protobuf:"bytes,2,opt,name=svr_name,json=svrName,proto3" json:"svr_name,omitempty"`
	Addr      string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RegisterServerReq) Reset() {
	*x = RegisterServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerReq) ProtoMessage() {}

func (x *RegisterServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerReq.ProtoReflect.Descriptor instead.
func (*RegisterServerReq) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServerReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterServerReq) GetSvrName() string {
	if x != nil {
		return x.SvrName
	}
	return ""
}

func (x *RegisterServerReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RegisterServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RegisterServerResp) Reset() {
	*x = RegisterServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerResp) ProtoMessage() {}

func (x *RegisterServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerResp.ProtoReflect.Descriptor instead.
func (*RegisterServerResp) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServerResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterServerResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnRegisterServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SvrName   string `protobuf:"bytes,2,opt,name=svr_name,json=svrName,proto3" json:"svr_name,omitempty"`
	Addr      string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *UnRegisterServerReq) Reset() {
	*x = UnRegisterServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterServerReq) ProtoMessage() {}

func (x *UnRegisterServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterServerReq.ProtoReflect.Descriptor instead.
func (*UnRegisterServerReq) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{2}
}

func (x *UnRegisterServerReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UnRegisterServerReq) GetSvrName() string {
	if x != nil {
		return x.SvrName
	}
	return ""
}

func (x *UnRegisterServerReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type UnRegisterServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UnRegisterServerResp) Reset() {
	*x = UnRegisterServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterServerResp) ProtoMessage() {}

func (x *UnRegisterServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterServerResp.ProtoReflect.Descriptor instead.
func (*UnRegisterServerResp) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{3}
}

func (x *UnRegisterServerResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnRegisterServerResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DiscoverServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SvrName   string `protobuf:"bytes,2,opt,name=svr_name,json=svrName,proto3" json:"svr_name,omitempty"`
}

func (x *DiscoverServerReq) Reset() {
	*x = DiscoverServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServerReq) ProtoMessage() {}

func (x *DiscoverServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServerReq.ProtoReflect.Descriptor instead.
func (*DiscoverServerReq) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverServerReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoverServerReq) GetSvrName() string {
	if x != nil {
		return x.SvrName
	}
	return ""
}

type DiscoverServerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DiscoverServerResp) Reset() {
	*x = DiscoverServerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eason_eason_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverServerResp) ProtoMessage() {}

func (x *DiscoverServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_eason_eason_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverServerResp.ProtoReflect.Descriptor instead.
func (*DiscoverServerResp) Descriptor() ([]byte, []int) {
	return file_api_eason_eason_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverServerResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DiscoverServerResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DiscoverServerResp) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DiscoverServerResp) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_api_eason_eason_proto protoreflect.FileDescriptor

var file_api_eason_eason_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2f, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x60, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x76, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x22, 0x3a, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x62, 0x0a, 0x13, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x76, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x22, 0x3c, 0x0a, 0x14, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x4c, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x76, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x5e, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32,
	0xe1, 0x02, 0x0a, 0x12, 0x45, 0x61, 0x73, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x71, 0x0a, 0x10, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6b, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x50, 0x73, 0x79, 0x63, 0x68, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x45, 0x6e,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_eason_eason_proto_rawDescOnce sync.Once
	file_api_eason_eason_proto_rawDescData = file_api_eason_eason_proto_rawDesc
)

func file_api_eason_eason_proto_rawDescGZIP() []byte {
	file_api_eason_eason_proto_rawDescOnce.Do(func() {
		file_api_eason_eason_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_eason_eason_proto_rawDescData)
	})
	return file_api_eason_eason_proto_rawDescData
}

var file_api_eason_eason_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_eason_eason_proto_goTypes = []interface{}{
	(*RegisterServerReq)(nil),    // 0: grpc.naming_server.eason.RegisterServerReq
	(*RegisterServerResp)(nil),   // 1: grpc.naming_server.eason.RegisterServerResp
	(*UnRegisterServerReq)(nil),  // 2: grpc.naming_server.eason.UnRegisterServerReq
	(*UnRegisterServerResp)(nil), // 3: grpc.naming_server.eason.UnRegisterServerResp
	(*DiscoverServerReq)(nil),    // 4: grpc.naming_server.eason.DiscoverServerReq
	(*DiscoverServerResp)(nil),   // 5: grpc.naming_server.eason.DiscoverServerResp
}
var file_api_eason_eason_proto_depIdxs = []int32{
	0, // 0: grpc.naming_server.eason.EasonNamingService.RegisterServer:input_type -> grpc.naming_server.eason.RegisterServerReq
	2, // 1: grpc.naming_server.eason.EasonNamingService.UnRegisterServer:input_type -> grpc.naming_server.eason.UnRegisterServerReq
	4, // 2: grpc.naming_server.eason.EasonNamingService.DiscoverServer:input_type -> grpc.naming_server.eason.DiscoverServerReq
	1, // 3: grpc.naming_server.eason.EasonNamingService.RegisterServer:output_type -> grpc.naming_server.eason.RegisterServerResp
	3, // 4: grpc.naming_server.eason.EasonNamingService.UnRegisterServer:output_type -> grpc.naming_server.eason.UnRegisterServerResp
	5, // 5: grpc.naming_server.eason.EasonNamingService.DiscoverServer:output_type -> grpc.naming_server.eason.DiscoverServerResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_eason_eason_proto_init() }
func file_api_eason_eason_proto_init() {
	if File_api_eason_eason_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_eason_eason_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eason_eason_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eason_eason_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eason_eason_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eason_eason_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eason_eason_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverServerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_eason_eason_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_eason_eason_proto_goTypes,
		DependencyIndexes: file_api_eason_eason_proto_depIdxs,
		MessageInfos:      file_api_eason_eason_proto_msgTypes,
	}.Build()
	File_api_eason_eason_proto = out.File
	file_api_eason_eason_proto_rawDesc = nil
	file_api_eason_eason_proto_goTypes = nil
	file_api_eason_eason_proto_depIdxs = nil
}
