// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user_info_server/user_info_server.proto

package user_info_server

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CommonHead) Validate() error {
	return nil
}
func (this *CommonRsp) Validate() error {
	return nil
}
func (this *UserInfo) Validate() error {
	return nil
}
func (this *RegisterReq) Validate() error {
	if this.UserInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserInfo", err)
		}
	}
	return nil
}
func (this *RegisterRsp) Validate() error {
	if this.CommonRsp != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommonRsp); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommonRsp", err)
		}
	}
	return nil
}
func (this *LoginReq) Validate() error {
	return nil
}
func (this *LoginRsp) Validate() error {
	if this.CommonRsp != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommonRsp); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommonRsp", err)
		}
	}
	if this.UserInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserInfo", err)
		}
	}
	return nil
}
func (this *GetUserInfoBySearchKeyReq) Validate() error {
	return nil
}
func (this *GetUserInfoBySearchKeyRsp) Validate() error {
	if this.CommonRsp != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommonRsp); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommonRsp", err)
		}
	}
	if this.UserInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserInfo", err)
		}
	}
	return nil
}
func (this *BatchGetUserInfoReq) Validate() error {
	return nil
}
func (this *BatchGetUserInfoRsp) Validate() error {
	if this.CommonRsp != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommonRsp); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommonRsp", err)
		}
	}
	for _, item := range this.UserInfo {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("UserInfo", err)
			}
		}
	}
	return nil
}
