server:
  server_name: user_info_server
  port: 50051
  log: /data/log/user_info_server.log
prometheus:
  ip: '0.0.0.0'
  port: 9093
mysql:
  master:
    ip: '118.195.204.214'
    port: 3306
    user: root
    passwd: qianhaiwaibao
  slave:
    ip: '159.75.15.177'
    port: 3306
    user: root
    passwd: qianhaiwaibao
etcd:
  ip: '159.75.15.177'
  port: 2379